import Foundation

struct SampleData {
    static let recipes = [
        Recipe(name: "Spaghetti Bolognese",
            category: "Main Course",
            ingredients: ["Spaghetti", "Ground Beef", "Tomato Sauce", "Onion", "Garlic"],
            instructions: "Cook the spaghetti. In a separate pan, cook the ground beef with onion and garlic. Add tomato sauce and simmer. Combine with spaghetti.",
            servings: 4,
            prepTime: "10 min",
            cookTime: "20 min",
            imageName: "spaghetti-bolognese",
            rating: 4),
        Recipe(name: "Chicken Curry",
            category: "Main Course",
            ingredients: ["Chicken Breast", "Curry Powder", "Coconut Milk", "Onion", "Garlic", "Ginger"],
            instructions: "Cook the chicken breast with onion, garlic, and ginger. Add curry powder and coconut milk. Simmer until chicken is cooked through.",
            servings: 4,
            prepTime: "15 min",
            cookTime: "25 min",
            imageName: "chicken-curry",
            rating: 4),
        Recipe(name: "Beef Stroganoff",
            category: "Main Course",
            ingredients: ["Beef", "Mushrooms", "Onion", "Sour Cream", "Garlic", "Paprika"],
            instructions: "Cook the beef with onion and garlic. Add mushrooms and cook until tender. Stir in sour cream and paprika. Serve over egg noodles.",
            servings: 4,
            prepTime: "10 min",
            cookTime: "30 min",
            imageName: "beef-stroganoff",
            rating: 4),
        Recipe(name: "Vegetable Stir Fry",
            category: "Main Course",
            ingredients: ["Broccoli", "Carrot", "Bell Pepper", "Soy Sauce", "Garlic", "Ginger"],
            instructions: "Stir-fry vegetables with garlic and ginger. Add soy sauce and cook until vegetables are tender. Serve with rice.",
            servings: 4,
            prepTime: "10 min",
            cookTime: "15 min",
            imageName: "vegetable-stir-fry",
            rating: 4),
        Recipe(name: "Fish Tacos",
            category: "Main Course",
            ingredients: ["Fish Fillets", "Tortillas", "Cabbage", "Lime", "Cilantro", "Sour Cream"],
            instructions: "Cook fish fillets and break into pieces. Assemble tacos with tortillas, fish, cabbage, lime, cilantro, and sour cream.",
            servings: 4,
            prepTime: "10 min",
            cookTime: "10 min",
            imageName: "fish-tacos",
            rating: 4),
        Recipe(name: "Caprese Salad",
            category: "Main Course",
            ingredients: ["Tomatoes", "Mozzarella", "Basil", "Olive Oil", "Balsamic Vinegar", "Salt"],
            instructions: "Layer tomatoes and mozzarella. Top with basil, olive oil, balsamic vinegar, and salt.",
            servings: 2,
            prepTime: "5 min",
            cookTime: "0 min",
            imageName: "caprese-salad",
            rating: 4),
        Recipe(name: "Pancakes",
            category: "Main Course",
            ingredients: ["Flour", "Milk", "Eggs", "Baking Powder", "Salt", "Butter"],
            instructions: "Mix ingredients to form batter. Cook pancakes on a griddle until golden brown.",
            servings: 4,
            prepTime: "5 min",
            cookTime: "15 min",
            imageName: "pancakes",
            rating: 4),
        Recipe(name: "Caesar Salad",
            category: "Main Course",
            ingredients: ["Romaine Lettuce", "Croutons", "Parmesan Cheese", "Caesar Dressing"],
            instructions: "Toss lettuce with croutons, parmesan cheese, and Caesar dressing.",
            servings: 2,
            prepTime: "5 min",
            cookTime: "0 min",
            imageName: "caesar-salad",
            rating: 4),
        Recipe(name: "Chicken Alfredo",
            category: "Main Course",
            ingredients: ["Chicken Breast", "Fettuccine", "Heavy Cream", "Parmesan Cheese", "Butter", "Garlic"],
            instructions: "Cook chicken and set aside. Prepare Alfredo sauce with heavy cream, parmesan cheese, butter, and garlic. Combine with cooked fettuccine and chicken.",
            servings: 4,
            prepTime: "10 min",
            cookTime: "20 min",
            imageName: "chicken-alfredo",
            rating: 4),
        Recipe(name: "Tuna Salad",
            category: "Main Course",
            ingredients: ["Tuna", "Mayonnaise", "Celery", "Onion", "Lemon Juice", "Salt"],
            instructions: "Mix all ingredients together. Serve on bread or lettuce.",
            servings: 2,
            prepTime: "10 min",
            cookTime: "0 min",
            imageName: "tuna-salad",
            rating: 4)
    ]
}
